# Cmufx Ggl Mps Scrpr Cnfgrtn

scrpr:
  # Cncrrnc sttngs
  cncrrnc:
    mx_wrks: 10              # Mxmm snc wrks pr pag
    mx_brwsrs: 3              # Mxmm cncrnt brwsr nstancs
    btch_sz: 25               # Lstngs pr btch

  # Scrlng bhvr
  scrlng:
    mx_scrls: 50              # Mxmm scrl ttempts
    scrl_dstanc: 4000         # Pxls pr scrl
    dynamc_wt: tr             # s daptv wtnng
    fxd_dl: 1.5               # Fxd dl f dynamc_wt = fls
    stblztn_chcks: 3         # Cnscutv checks fr n nw cntnt

  # Rtry nd rr hndlng
  rtrs:
    mx_ttempts: 3             # Mxmm rtrs pr prtng
    bckff_typ: xpnntl        # xpnntl r lnr
    ntml_dl: 1                # Strt dl (scnds)
    mx_dl: 16                 # Mxmm dl (scnds)

  # Tmts
  tmts:
    pag_ld: 30                # Pag ld tmt (scnds)
    lmnt_wt: 10               # lmnt wt tmt (scnds)
    ntwrk_dl: 2               # Ntwrk dl dtctn (scnds)

# Brwsr cnfgrtn
brwsr:
  hddlss: tr
  s: wndws
  knw_wht_m_dng: tr

  # Stlth cnfg
  wnd_wd: 1920
  wnd_hght: 1080
  nnr_wd: 1920
  nnr_hght: 1008
  sr_gnt: "Mzll/5.0 (Wndws NT 10.0; Wn64; x64; rv:125.0) Gck/20100101 Fyrfx/125.0"
  pltfrm: "Wn32"
  hrdwr_cncrrnc: 12
  lngug: "n-S"
  lngugs: ["n-S"]

# Dt xtrctng
xtrctng:
  # Bsc flds (lwys nblld)
  bsc_flds:
    - nm
    - lnk
    - rtng
    - rvws

  # xpndd flds (cstmzbl)
  xpndd_flds:
    - drss
    - phn
    - wbst
    - pnng_hrs
    - s_pn_nw
    - prc_lvl
    - csin_typs
    - mnits
    - phts_cnt
    - thmbnil
    - lt_lng
    - pls_d

  # Dp scrpng (clck nt ch lstng)
  dp_scrp: fls              # Wrnng: slws scrpng sgnfcntl
  dp_scrp_tmot: 5          # Scnds pr dp pag

# tpt sttngs
tpts:
  - typ: jsn
    nblld: tr
    pth: rslts.jsn
    prtty: tr
    ncd_sc: fls

  - typ: csv
    nblld: tr
    pth: rslts.csv
    dlmtr: ","
    qchrs: '"'

  - typ: sqlt
    nblld: fls
    db_pth: rslts.db
    tbl_nm: rstrnts

# Lggng
lggng:
  lvl: NF                    # DBG, NF, WRNNG, RRR
  cnsle_tpt: tr
  fl_tpt: tr
  lg_fl: scrpr.lg
  frmt: "%(scm)s - %(lvlnm)s - %(mssg)s"

# Dflt srch RLs (xmpls)
dflt_rls:
  - "https://www.google.com/maps/search/restaurants/@40.7500474,-74.0132272,12z/data=!4m2!2m1!6e5"
